CREATE TABLE locations (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
name VARCHAR2(200) NOT NULL,
category VARCHAR2(100), -- e.g., Transport, Shopping, Accommodation, Sightseeing
address VARCHAR2(400),
description CLOB
);

INSERT INTO locations (name, category, address, description) VALUES ('Central Station', 'Transport', '123 Main St', 'Major transit hub with buses and metro.');
INSERT INTO locations (name, category, address, description) VALUES ('City Mall', 'Shopping', '45 Commerce Ave', 'Large mall with food court and multiplex.');
COMMIT;
